taxi_rides_ny:
  outputs:
    dev:
      dataset: nytaxi
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: credentials.json
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      type: bigquery
    prod:
      dataset: dbt_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: credentials.json
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      type: bigquery
  target: dev
